multi_Python/django_second/mysite_base/blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    # /blog/
    path('', PostLV.as_view(), name='index'),

    # /blog/post
    path('post/', PostLV.as_view(), name='post_list'),

    # /blog/post/{slug}
    path('post/<str:slug>', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    path('archive/', PostAV.as_view(), name='post_archive'),

    # Example: /blog/2021/
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2021/01/
    path('<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2021/01/21/
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/ -> http://127.0.0.1:8000/blog/today/
    path('today/', PostTAV.as_view(), name='post_today_archive'),

    # Search: /search/ -> http://127.0.0.1:8000/blog/search/
    path('search/', SearchFormView.as_view(), name='search'),
]

multi_Python/django_second/mysite_base/bookmark/urls.py
from django.conf.urls import url
from django.urls import path

from bookmark.views import BookmarkLV, BookmarkDV

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

multi_Python/django_second/mysite_base/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),

    # http://127.0.0.1:8000/ -> home page 
    path('', HomeView.as_view(), name='home'),

    path('bookmark/', include('bookmark.urls', namespace='bookmark')),
    path('blog/', include('blog.urls', namespace='blog')),
]

multi_Python/django_second/mysite_base/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model): 
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for this alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        # ordering = ('modify_date','author')        # asc & author
        ordering = ('-modify_date',)        # desc, 
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,)) # -> 1st post -> /blog/post/1st-post

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()
    

multi_Python/django_second/mysite_base/bookmark/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return self.title

multi_Python/django_second/mysite_base/blog/forms.py
# forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Keyword')

multi_Python/django_second/mysite_base/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView
from django.views.generic.dates import MonthArchiveView, DayArchiveView, TodayArchiveView
from blog.models import Post

# Search 기능 추가 
from blog.forms import PostSearchForm
from django.views.generic.edit import FormView
from django.db.models import Q
from django.shortcuts import render

# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = "blog/post_all.html"
    context_object_name = "posts" #object_list 
    
    paginate_by = 3

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = "modify_date"

class PostYAV(YearArchiveView):
    model = Post
    make_object_list = True
    date_field = "modify_date"

class PostMAV(MonthArchiveView):
    model = Post
    date_field = "modify_date"
    month_format = "%m"

class PostDAV(DayArchiveView):
    model = Post
    date_field = "modify_date"
    month_format = "%m"

class PostTAV(TodayArchiveView):
    model = Post
    date_field = "modify_date"
    month_format = "%m"

class SearchFormView(FormView):
    form_class = PostSearchForm # forms.py에 생성
    template_name = "blog/post_search.html"

    def form_valid(self, form):
        schword = self.request.POST['search_word']
        post_list = Post.objects.filter(Q(title__icontains=schword) | Q(description__icontains=schword) | Q(content__icontains=schword)).distinct()

        # 검색된 결과 
        context = {}
       
        context['form'] = form
        context['search_keyword'] = schword
        context['search_list'] = post_list

        return render(self.request, self.template_name, context)

multi_Python/django_second/mysite_base/bookmark/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

#--- ListView
class BookmarkLV(ListView):
	model = Bookmark

#--- DetailView
class BookmarkDV(DetailView):
	model = Bookmark

multi_Python/django_second/mysite_base/mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = "home.html"

multi_Python/django_second/mysite_base/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}Post List{% endblock %}

{% block content %}
<div id="content">
    <h1>Blog List</h1>

    <!-- display blog list -->
    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        {{ post.modify_date|date:"Y-m-d H:i" }}
        <p>{{ post.description }}</p>
    {% endfor %}
    <br/>

    <!-- paging link -->
    <div>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}
        
        [ Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages}} ]

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </div>
</div>    
{% endblock %}

multi_Python/django_second/mysite_base/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}날짜별 포스트{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Archives until {% now "Y m d" %}</h1>
    <ul>
        {% for date in date_list %}
            <li style="display: inline;">
                <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">{{date|date:'Y'}}</a>
            </li> | 
        {% endfor %}
    </ul>
    <br/>
    <div>
        <ul>
        {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

multi_Python/django_second/mysite_base/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}일별 포스트{% endblock %}

{% block content %}
<div id="content">
    <h1>일별 등록된 게시물 {{ day|date:'Y-m-d' }}</h1>

    <div>
        <ul>
        {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}    

multi_Python/django_second/mysite_base/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}월별 포스트{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Archives for {{ month|date:'Y, N' }}</h1>
    <ul>
        {% for date in date_list %}
            <li style="display: inline;">
                <a href="{% url 'blog:post_day_archive' date|date:'Y' date|date:'m' date|date:'d'%}">{{date|date:'Y-m-d'}}</a>
            </li> | 
        {% endfor %}
    </ul>
    <br/>
    <div>
        <ul>
        {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

multi_Python/django_second/mysite_base/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}년도별 포스트{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Archives for {{ year|date:'Y' }}</h1>
    <ul>
        {% for date in date_list %}
            <li style="display: inline;">
                <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'m'%}">{{date|date:'b'}}</a> | 
            </li>
        {% endfor %}
    </ul>
    <br/>
    <div>
        <ul>
        {% for post in object_list %}
            <li>
                {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

multi_Python/django_second/mysite_base/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}Post Detail{% endblock %}

{% block content %}
<div id="content">
    <h2>{{ object.title }}</h2>

    <!-- previous or next post link -->
    <p class="other_posts">
        <a href="{{ object.get_previous_post.get_absolute_url }}">
            {{ object.get_previous_post }}
        </a>
        |
        <a href="{{ object.get_next_post.get_absolute_url }}">
            {{ object.get_next_post }}
        </a>
    </p>

    <!-- date -->
    <p class="date">
        {{ object.modify_date|date:"Y-m-d H:i" }}
    </p>
    <br/>
    <!-- post content -->
    <div class="body">
        {{ object.content|linebreaks }}
    </div>
</div>
{% endblock %}

multi_Python/django_second/mysite_base/blog/templates/blog/post_search.html
<!-- base 페이지 상속 -->
{% extends "base.html" %}
{% block title %} 검색 페이지 {% endblock %}

{% block content %}
<div id="content">
    <h1> Blog Search Engine </h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Search">
    </form>
    <br/><br/>
    {% if search_list %}
        {% for post in search_list %}
            <h3>{{post.title}}</h3>
            {{post.modify_date|date:"Y-m-d"}}
            <p>{{post.description}}</p>
        {% endfor %}
    {% elif search_keyword %}
        [{{ search_keyword }}]의 검색 결과가 없습니다.
    {% endif %}
</div>
{% endblock %}

multi_Python/django_second/mysite_base/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}
{% block title %} Django Bookmark Detail {% endblock %}

{% block content %}
<div id="content">
	<h1>{{ object.title }}</h1>
	<ul>
		<li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
	</ul>
</div> 
{% endblock %}

multi_Python/django_second/mysite_base/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}
{% block title %} Django Bookmark List {% endblock %}

{% block content %}
<div id="content">
	<h1>Bookmark List</h1>
	<ul>
	{% for bookmark in object_list %}
		<li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
	{% endfor %}
	</ul>
</div> 
{% endblock %}

multi_Python/django_second/mysite_base/templates/base.html
<!DOCTYPE html>
<html lang="ko">

    <head>
        <title>{% block title %}Django Web Programming{% endblock %}</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/base.css' %}{% endblock %}" />
        <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

    </head>

    <body>

        <div id="header">
            <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
            <h4 class="welcome">Welcome, <a href="#">OOO</a> /
                <a href="#">Change Password</a> /
                <a href="#">Logout</a>
            </h4>
        </div>

        <div id="menu">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li><a href="#">Photo</a></li>
            <li><a href="#">Add&bigtriangledown;</a>
                <ul>
                    <li><a href="#">Bookmark</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Photo</a></li>
                </ul>
            </li>
            <li><a href="#">Change&bigtriangledown;</a>
                <ul>
                    <li><a href="#">Bookmark</a></li>
                    <li><a href="#">Blog</a></li>
                <li><a href="#">Photo</a></li>
                </ul>
            </li>

            <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
            <li><a href="{% url 'blog:search' %}">Search</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
        </div>

        {% block content %}{% endblock %}

        {% block footer %}{% endblock %}

    </body>

</html>

multi_Python/django_second/mysite_base/templates/home.html
{% extends "base.html" %}

{% block title%}home.html{% endblock %}

{% load static %}
{% block extrastyle %}{% static 'css/home.css' %}{% endblock %}

{% block content %}
    <div id="content_home">
        <div id="homeimg">
            <img src="{% static 'img/django-actor-big.jpg' %}" style="height: 400px;"/>
            <h4 style="margin: 0;">This is Django powered web site.</h4>
        </div>
    </div>

    {% comment %} <div style="margin-top: 100px;">
    <form action="[서버의 URL]" method="get">
        키워드 검색: <input type="text" name="search_word"> <br/>
        검색 범위: <input type="radio" name="category"> IT &nbsp;&nbsp;
                <input type="radio" name="category"> 여행
                <br>
        <input type="submit" value="검색">
    </form>
    </div> {% endcomment %}
{% endblock %}

{% block footer %}
    <div id="footer">
        &copy; This is FOOTER area.
    </div>
{% endblock %}