assignment/project1/api/urls.py
from django.contrib import admin
from django.urls import path, include
from project1.views import HomeView
from api.views import UserViewSet
from rest_framework import routers

routers = routers.DefaultRouter()
routers.register('news',UserViewSet)


urlpatterns = [
    path('', include(routers.urls)),
]

assignment/project1/news/urls.py
from django.urls import path
from news.views import *

app_name = 'news'

urlpatterns = [
    path('it/', ItNews, name='it'),
    path('sport/', SportNews, name='sport'),
    path('economy/', EconomyNews, name='economy'),
    path('stock/', Stockview, name='stock'),
]

assignment/project1/project1/urls.py
from django.contrib import admin
from django.urls import path, include
from project1.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls', namespace='news')),
    path('',HomeView.as_view(), name='home'),
    path('api/', include('api.urls')),
    path('weather/', include('weather.urls', namespace='weather')),
]

assignment/project1/weather/urls.py
from django.urls import path
from weather.views import *

app_name = 'weather'

urlpatterns = [
    path('', Search, name="weather_search"),
]

assignment/project1/api/models.py
from django.db import models

# Create your models here.

assignment/project1/news/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class News(models.Model):
    
    kind = models.CharField('KIND', max_length=50, blank=False)
    title = models.CharField('TITLE', max_length=100)
    author = models.CharField('AUTHOR', max_length=50)
    display = models.CharField('DISPLAY', max_length=200)

    def __str__(self):
        return self.display

assignment/project1/weather/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Weather(models.Model):
    
    city = models.CharField('CITY', max_length=100, blank=False)
    temperature = models.CharField('TEMPERATURE', max_length=100)
    skt = models.CharField('SKY', max_length=100)

    def __str__(self):
        return self.city

assignment/project1/api/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework import viewsets
from news.serializers import UserSerializer
from news.models import News

class UserViewSet(viewsets.ModelViewSet):
    queryset = News.objects.all()
    serializer_class = UserSerializer

assignment/project1/news/views.py
from django.shortcuts import render
from django.urls import reverse
from django.db.models import Q
import os
# Create your views here.
from news.models import News
from django.views.generic import ListView,FormView




def ItNews(request):
    context = {}
    if 'kind' in request.GET:
        os.chdir('/Users/bumjh/Desktop/Study/assignment/project1/Itnews')
        os.system('scrapy crawl itbots')
        temp = News.objects.filter(Q(kind__icontains="IT"))
        context = {'News' : temp}
    return render(request, 'news/news_it.html', context)


def SportNews(request):
    context = {}
    if 'kind' in request.GET:
        os.chdir('/Users/bumjh/Desktop/Study/assignment/project1/Itnews')
        os.system('scrapy crawl sportbots')
        temp = News.objects.filter(Q(kind__icontains="SPORT"))
        context = {'News' : temp}
    return render(request, 'news/news_sport.html', context)
    

def EconomyNews(request):
    context = {}
    if 'kind' in request.GET:
        os.chdir('/Users/bumjh/Desktop/Study/assignment/project1/Itnews')
        os.system('scrapy crawl economybots')
        temp = News.objects.filter(Q(kind__icontains="ECONOMY"))
        context = {'News' : temp}
    return render(request, 'news/news_economy.html', context)

def Stockview(request):
    context = {}
    if request.method == 'GET':
        if 'name' in request.GET:
            temp = request.GET['name']
            stock = News.objects.filter(Q(kind__icontains="STOCK"))
            context = {'Stock' : stock}
    return render(request, 'news/stock.html', context)

assignment/project1/project1/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = "base.html"

assignment/project1/weather/views.py
from django.shortcuts import render
from django.urls import reverse
from django.db.models import Q
import os
import urllib
import json
# Create your views here.
from news.models import News
from django.views.generic import ListView,FormView

# Create your views here.
def Search(request):
    context = {}
    if request.method == 'GET':
        if 'city' in request.GET:
            temp = request.GET['city']
            client_key = "9d4bd7ac6c4ca6ea0d7872755dc9af77"
            api_call = "https://api.openweathermap.org/data/2.5/weather?q={}&appid={}&lang=kr".format(temp, client_key)
            req = urllib.request.urlopen(api_call)
            if req.getcode() == 200:
                body = req.read()
                result = json.loads(body.decode('utf-8'))
                context = {'weather' : result}
    return render(request, 'weather/weather_search.html', context)

assignment/project1/news/templates/news/news_economy.html
{% extends "base.html" %}

{% block title %}EconomyNews{% endblock %}

{% block content %}
<div id="content">
    <h2>EconomyNews</h2>
    <form action = "" method="GET">
        {% csrf_token %}
        <input type="hidden" name="kind" value="ECONOMY">
        <input type="submit" value="최신 데이터 가져오기">
    </form>
    {% if News %}
        {% for news in News %}
        <h3>{{news.title}}</h3>
        <h5>{{news.display}}</h5>
        {% endfor %}
    {% endif %}

    <!-- previous or next post link -->
    <!-- <p class="other_posts">
        <a href="{{ object.get_previous_post.get_absolute_url }}">
            {{ object.get_previous_post }}
        </a>
        |
        <a href="{{ object.get_next_post.get_absolute_url }}">
            {{ object.get_next_post }}
        </a>
    </p> -->
</div>
{% endblock %}

assignment/project1/news/templates/news/news_it.html
{% extends "base.html" %}

{% block title %}ItNews{% endblock %}

{% block content %}
<div id="content">
    <h2>ItNews</h2>
    <form action = "" method="GET">
        {% csrf_token %}
        <input type="hidden" name="kind" value="IT">
        <input type="submit" value="최신 데이터 가져오기">
    </form>
    {% if News %}
        {% for news in News %}
        <h3>{{news.title}}</h3>
        <h5>{{news.display}}</h5>
        {% endfor %}
    {% endif %}

    <!-- previous or next post link -->
    <!-- <p class="other_posts">
        <a href="{{ object.get_previous_post.get_absolute_url }}">
            {{ object.get_previous_post }}
        </a>
        |
        <a href="{{ object.get_next_post.get_absolute_url }}">
            {{ object.get_next_post }}
        </a>
    </p> -->
</div>
{% endblock %}

assignment/project1/news/templates/news/news_sport.html
{% extends "base.html" %}

{% block title %}SportNews{% endblock %}

{% block content %}
<div id="content">
    <h2>SportNews</h2>
    <form action = "" method="GET">
        {% csrf_token %}
        <input type="hidden" name="kind" value="SPORT">
        <input type="submit" value="최신 데이터 가져오기">
    </form>
    {% if News %}
        {% for news in News %}
        <h3>{{news.title}}</h3>
        <h5>{{news.display}}</h5>
        {% endfor %}
    {% endif %}

    <!-- previous or next post link -->
    <!-- <p class="other_posts">
        <a href="{{ object.get_previous_post.get_absolute_url }}">
            {{ object.get_previous_post }}
        </a>
        |
        <a href="{{ object.get_next_post.get_absolute_url }}">
            {{ object.get_next_post }}
        </a>
    </p> -->
</div>
{% endblock %}

assignment/project1/news/templates/news/stock.html
{% extends "base.html" %}

{% block title %}SportNews{% endblock %}

{% block content %}
<div id="content">
    <h2>Stock</h2>
    <form action = "" method="GET">
        {% csrf_token %}
        <input type="text" name="name" id="name">
        <input type="submit" value="정보 가져오기">
    </form>

    <h2>{{stock}}</h2>
    <!-- previous or next post link -->
    <!-- <p class="other_posts">
        <a href="{{ object.get_previous_post.get_absolute_url }}">
            {{ object.get_previous_post }}
        </a>
        |
        <a href="{{ object.get_next_post.get_absolute_url }}">
            {{ object.get_next_post }}
        </a>
    </p> -->
</div>
{% endblock %}

assignment/project1/templates/base.html
<!DOCTYPE html>
<html lang="ko">

    <head>
        <title>{% block title %}project1{% endblock %}</title>

        <!-- {% load static %}
        <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/base.css' %}{% endblock %}" />
        <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" /> -->

    </head>

    <body>

        <div id="header">
            <h2 class="maintitle">first project</h2>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'news:it'%}">ItNews</a></li>
                <li><a href="{% url 'news:sport'%}">SportNews</a></li>
                <li><a href="{% url 'news:economy'%}">EconomyNews</a></li>
                <li><a href="{% url 'news:stock'%}">Stock</a></li>
                <li><a href="{% url 'weather:weather_search'%}">Weather</a></li>
            </ul>
        </div>
        {% block content %}{% endblock %}
        

        {% block footer %}{% endblock %}

    </body>

</html>

assignment/project1/weather/templates/weather/weather_search.html
{% extends "base.html" %}

{% block title %}Weather{% endblock %}

{% block content %}
<div id="content">
    <h2>Weather</h2>
    <form action = "" method="GET">
        {% csrf_token %}
        <label for="city">Enter city(english):</label>
        <input type="text" id="city" name="city">
        <input type="submit" value="날씨 검색">
    </form>
    <h3>이름 : {{weather.name}}</h3>
    <h3>날씨 : {{weather.weather.0.description}}</h3>
    <h3>온도 : {{weather.main.temp}}</h3>
    <h3>풍속 : {{weather.wind.speed}}</h3>
    

    <!-- previous or next post link -->
    <!-- <p class="other_posts">
        <a href="{{ object.get_previous_post.get_absolute_url }}">
            {{ object.get_previous_post }}
        </a>
        |
        <a href="{{ object.get_next_post.get_absolute_url }}">
            {{ object.get_next_post }}
        </a>
    </p> -->
</div>
{% endblock %}